name: dangal_games_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.01

environment:
  sdk: ">=2.7.0 <3.0.0" #to be changed

dependencies:
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  flutter_easyloading: ^3.0.3
  google_sign_in: ^5.3.1
  flare_flutter: ^3.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9 
  connectivity: ^3.0.6 
  paytm_allinonesdk: ^1.1.7
  sizer: ^2.0.15
  cupertino_icons: ^1.0.4 
  permission_handler: ^9.0.2
  custom_navigator:
  toast: ^0.3.0
  dashed_container:
  flutter_switch: ^0.3.2
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  open_mail_app: ^0.2.0
  flutter_webview_plugin: ^0.4.0 
  intl: ^0.17.0 
  web_socket_channel: ^2.2.0
  webview_flutter: ^3.0.4
  android_intent: ^2.0.2
  path_provider: ^2.0.10
  device_apps: ^2.2.0
  flutter_downloader: ^1.7.4
  page_transition: ^2.0.5
  circular_countdown_timer: ^0.2.0
  splashscreen:
  flutter_background: ^1.1.0
  flutter_image_compress: ^1.1.0 
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.2
  flutter_fgbg: ^0.2.0 
  firebase_dynamic_links: ^4.0.7 
  get_it: ^7.2.0
  flutter_inappwebview: ^5.4.3+7 
  screen_state: ^2.0.0
  cashfree_pg: ^2.0.10+30
  clevertap_plugin: ^1.5.1
  devicelocale: ^0.5.2 
  advertising_identifier: ^0.1.3 
  flutter_local_notifications: ^9.5.3+1 
  firebase_messaging: ^11.2.7
  device_info: ^2.0.3
  easy_localization: ^3.0.0
  get_version: 
  singular_flutter_sdk: ^1.0.6 
  overlay_support: ^1.2.1
  flutter_notification_channel: ^2.0.0
  carousel_slider: ^4.1.1
  firebase_crashlytics: ^2.5.2
  intent: ^1.3.4
  firebase_performance: ^0.8.0+6
  sms_autofill: ^2.2.0
  package_info: ^2.0.2 
  razorpay_flutter: ^1.3.0 
  firebase_analytics: ^9.1.1 
  location: ^4.4.0
  ota_update: ^4.0.1
  flutter_cache_manager: ^3.3.0
  dio: ^4.0.6
  flutter_svg: ^1.0.3
  social_share: ^2.2.1
  flutter_flavor: ^3.0.3
  otp_text_field: ^1.1.3
  flutter_widget_from_html: ^0.8.3
  in_app_update: ^3.0.0



dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_flavor:
  dimensions:
    android: "flutter-flavor"

  flavors:
    dev:
      android:
        name: "Dev App"
        applicationId: "com.devapp.dangalgames"

    prod:
      android:
        name: "Prod App"
        applicationId: "com.app.dangalgames"

    prod_co_in:
      android:
        name: "Prod CO IN App"
        applicationId: "com.app.dangalgames.co.in"

    dev_playstore:
      android:
        name: "Dev Play Store App"
        applicationId: "com.devapp.play.dangalgames"

    prod_playstore:
      android:
        name: "Prod Play Store App"
        applicationId: "com.app.play.dangalgames"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class
  uses-material-design: true

  assets:
    - assets/html/
    - assets/images/
    - assets/translations/
    - assets/images/leaderboard_icons/
    - assets/images/icons/
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/images/gifs/
  




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-andgmail_-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#cmd to build apk flavor wise
#flutter build apk --flavor dev -t lib/main_dev.dart --split-per-abi --no-shrink
#flutter build apk --flavor prod -t lib/main_prod.dart --split-per-abi --no-shrink
#flutter build apk --flavor prod_co_in -t lib/main_prod_co_in.dart --split-per-abi --no-shrink
#flutter build apk --flavor dev_playstore -t lib/main_dev_playstore.dart --split-per-abi --no-shrink
#flutter build apk --flavor prod_playstore -t lib/main_prod_playstore.dart --split-per-abi --no-shrink
#flutter pub run flutter_flavor:main